server:
  port: 8081
spring:
  profiles:
    active: prod
  application:
    name: hmdp
  datasource:
    driver-class-name: ${hmdp.datasource.driver-class-name}
    url: ${hmdp.datasource.url}
    username: ${hmdp.datasource.username}
    password: ${hmdp.datasource.password}
  redis:
    host: ${hmdp.redis.host}
    port: ${hmdp.redis.port}
    password: ${hmdp.redis.password}
    lettuce:
      pool:
        max-active: ${hmdp.redis.lettuce.pool.max-active}
        max-idle: ${hmdp.redis.lettuce.pool.max-idle}
        min-idle: ${hmdp.redis.lettuce.pool.min-idle}
        time-between-eviction-runs: ${hmdp.redis.lettuce.pool.time-between-eviction-runs}
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug