---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jiuzhou.
--- DateTime: 2024/9/8 15:25
---

local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

-- 判断库存是否充足
if (tonumber(redis.call('get',stockKey)) <= 0) then
    --库存不足，返回1
    return 1
end
-- 判断是否存在订单
if (redis.call('sismember',orderKey,userId)==1) then
    -- 已经存在订单，返回2
    return 2
end
-- 进行库存的扣减和下单
redis.call('incrby',stockKey,-1)
-- 进行订单的保存，确保一人一单
redis.call('sadd',orderKey,userId)
-- 发送消息到队列中
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId);
return 0
