---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jiuzhou.
--- DateTime: 2024/9/7 14:29
---
local id = redis.call('get',KEYS[1])
if(id==ARGV[1]) then
    --释放锁
    return redis.call('del',KEYS[1])
end
return 0